apiVersion: v1
kind: Service
metadata:
  labels:
    app: ueransim
    app.kubernetes.io/managed-by: Helm
    component: gnb
  name: tester-n1-service
spec:
  clusterIP: None
  ports:
  - name: n1
    port: 4997
    protocol: UDP
    targetPort: n1-ue
  selector:
    app: tester
    component: ue
  type: ClusterIP

