apiVersion: v1
kind: Service
metadata:
  labels:
    app: ueransim
    app.kubernetes.io/managed-by: Helm
    component: gnb
  name: tester-n2-service
spec:
  clusterIP: None
  ports:
  - name: n2
    port: 8805
    protocol: TCP
    targetPort: 8805
  selector:
    app: tester
    component: ue
  type: ClusterIP

